name: Django Auto Deploy

on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_IP }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Pulling latest code..."
            cd /home/ubuntu/apwebstack
            git reset --hard
            git pull origin main

            echo "Activating virtual environment..."
            source /home/ubuntu/apwebstack/venv/bin/activate
            
            
           
            cd /home/ubuntu/apwebstack/src 

            echo "Applying make migrations..."
            python manage.py makemigrations

            echo "Applying migrate..."
            python manage.py migrate
            
            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting Gunicorn..."
            sudo systemctl restart gunicorn

            echo "Reloading NGINX..."
            sudo systemctl reload nginx

            echo "Deployment complete!"
